### PR TITLE
🚑🐛 Fixed a major

### LINKED ISSUE #2: Date Issues
The newest Fix introduces a **major** bug.
When executing the script, the content of the mail will be the plan for Thursday.

### PR DESCRIPTION
**Pull request by Ron31**
Fixed:
- Incorrect behavior with schedules

should fix #2

### CODE REVIEW

**Comment by kdev** [comment]
Is this done?

**Comment by Ron31** [comment]
Should be done. Try it please before merging and request changes otherwise.

**Comment by kdev** [comment]
@all-contributors please add @Ron31 for code and maintenance

**Review by kdev — APPROVED** [review]
@Ron31 tested it!

**Pull request merged**
